site_name: Knowledge Base
repo_url: https://github.com/minor-league-esports/knowledgeBase
theme:
  name: material
nav:
  - Home: index.md
  - Departments:
    - Rocket League Operations: departments/rocket-league-operations.md
    - Trackmania Operations: departments/trackmania-operations.md
    - Community: departments/community.md
    - Development:
      - Overview: departments/development/development.md
      - New Team Members: departments/development/new-team-members.md
      - Systems:
        - Overview: departments/development/systems/systems-overview.md
        - Modmail KB: departments/development/systems/modmail.md
        - Sprocket Identity System: departments/development/systems/sprocket-identity-system.md
    - Marketing: departments/marketing.md
    - Production: departments/production.md
